import { z } from 'zod';

export const inventoryAdjustmentSchema = z.object({ delta: z.coerce.number().int().min(-100_000).max(100_000).refine((value) => value !== 0), reason: z.string().trim().min(3).max(255) });
export const createStaffSchema = z.object({ name: z.string().trim().min(2).max(120), email: z.string().trim().email().max(191), password: z.string().min(10).max(128) });
export const mediaAssetSchema = z.object({ url: z.string().url().max(2048), publicId: z.string().trim().min(1).max(255).optional(), altText: z.string().trim().max(255).optional(), width: z.coerce.number().int().positive().optional(), height: z.coerce.number().int().positive().optional() });
export const bannerSchema = z.object({ assetId: z.string().cuid(), title: z.string().trim().max(160).nullable().optional(), subtitle: z.string().trim().max(255).nullable().optional(), linkUrl: z.string().url().max(2048).nullable().optional(), sortOrder: z.coerce.number().int().min(0).max(999).default(0), active: z.boolean().default(true), startsAt: z.coerce.date().nullable().optional(), endsAt: z.coerce.date().nullable().optional() });
export const productSchema = z.object({ categoryId: z.string().cuid(), name: z.string().trim().min(2).max(160), slug: z.string().trim().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(180), description: z.string().trim().max(10_000).nullable().optional(), material: z.string().trim().min(2).max(100), priceCents: z.coerce.number().int().min(0).max(10_000_000), weightGrams: z.coerce.number().int().min(1).max(100_000), active: z.boolean().optional() });
export const productPatchSchema = productSchema.partial();
export const productOptionSchema = z.object({ variantOptionId: z.string().cuid(), imageAssetId: z.string().cuid().nullable().optional(), sortOrder: z.coerce.number().int().min(0).max(999).default(0), variants: z.array(z.object({ sizeId: z.string().cuid(), sku: z.string().trim().min(2).max(100), priceCents: z.coerce.number().int().min(0).max(10_000_000).nullable().optional(), openingStock: z.coerce.number().int().min(0).max(100_000).default(0) })).min(1) });
export const productOptionPatchSchema = z.object({ imageAssetId: z.string().cuid().nullable().optional(), sortOrder: z.coerce.number().int().min(0).max(999).optional(), active: z.boolean().optional() }).refine((value) => Object.keys(value).length > 0);
export const productVariantPatchSchema = z.object({ sku: z.string().trim().min(2).max(100).optional(), priceCents: z.coerce.number().int().min(0).max(10_000_000).nullable().optional(), active: z.boolean().optional() }).refine((value) => Object.keys(value).length > 0);
export const productImageSchema = z.object({ assetId: z.string().cuid(), productOptionId: z.string().cuid().nullable().optional(), type: z.enum(['PRIMARY', 'SECONDARY']).default('SECONDARY'), sortOrder: z.coerce.number().int().min(0).max(999).default(0) });
export const categorySchema = z.object({ name: z.string().trim().min(2).max(100), slug: z.string().trim().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(120), imageAssetId: z.string().cuid().nullable().optional(), sortOrder: z.coerce.number().int().min(0).max(999).default(0), active: z.boolean().default(true) });
export const variantOptionSchema = z.object({ type: z.enum(['COLOR', 'PRINT']), name: z.string().trim().min(2).max(100), slug: z.string().trim().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(120), swatchHex: z.string().trim().regex(/^#[0-9a-fA-F]{3,8}$/).nullable().optional(), active: z.boolean().default(true) });
